[package]
name = "check-buddy"
description = "The main system of check buddy"
license-file = "LICENSE.md"
version = "0.3.2"
edition = "2021"
authors = ["Ramon van Sprundel <ramonvansprundel@gmail.com>"]
repository = "https://github.com/van-sprundel/check-buddy"
categories = ["games", "algorithms"]
keywords = ["chess", "chess-engine"]

[dependencies]
rand = "0.9"
anyhow = "1"
thiserror = "2"
arrayvec = "0.7.6"

[dev-dependencies]
calamine = "0.32.0"
criterion = "0.8.1"
csv = "1.4.0"
iai-callgrind = "0.16"

[[bench]]
name = "generate_moves"
harness = false

[[bench]]
name = "generate_moves_iai"
harness = false
